version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
